# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/bd/cryptoprocessor/ip/cryptoprocessor_ComputeCoreWrapper_0_0/cryptoprocessor_ComputeCoreWrapper_0_0.xci
# IP: The module: 'cryptoprocessor_ComputeCoreWrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/INS_RAM/INS_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/BRAM64_512/BRAM64_512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM64_512 || ORIG_REF_NAME==BRAM64_512} -quiet] -quiet

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/q_const_mult/q_const_mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==q_const_mult || ORIG_REF_NAME==q_const_mult} -quiet] -quiet

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/mu_const_mult/mu_const_mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mu_const_mult || ORIG_REF_NAME==mu_const_mult} -quiet] -quiet

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/mult_64/mult_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_64 || ORIG_REF_NAME==mult_64} -quiet] -quiet

# XDC: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/BRAM64_512/BRAM64_512_ooc.xdc

# XDC: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/bd/cryptoprocessor/ip/cryptoprocessor_ComputeCoreWrapper_0_0/cryptoprocessor_ComputeCoreWrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cryptoprocessor_ComputeCoreWrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/bd/cryptoprocessor/ip/cryptoprocessor_ComputeCoreWrapper_0_0/cryptoprocessor_ComputeCoreWrapper_0_0.xci
# IP: The module: 'cryptoprocessor_ComputeCoreWrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/INS_RAM/INS_RAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/BRAM64_512/BRAM64_512.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM64_512 || ORIG_REF_NAME==BRAM64_512} -quiet] -quiet

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/q_const_mult/q_const_mult.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==q_const_mult || ORIG_REF_NAME==q_const_mult} -quiet] -quiet

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/mu_const_mult/mu_const_mult.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mu_const_mult || ORIG_REF_NAME==mu_const_mult} -quiet] -quiet

# IP: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/mult_64/mult_64.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_64 || ORIG_REF_NAME==mult_64} -quiet] -quiet

# XDC: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/ip/BRAM64_512/BRAM64_512_ooc.xdc

# XDC: /home/jharing/git/2nd/chw2022g3/project_1/project_1.srcs/sources_1/bd/cryptoprocessor/ip/cryptoprocessor_ComputeCoreWrapper_0_0/cryptoprocessor_ComputeCoreWrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cryptoprocessor_ComputeCoreWrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
