#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Dec 14 22:44:01 CET 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_polmul_behav -key {Behavioral:sim_1:Functional:tb_polmul} -tclbatch tb_polmul.tcl -protoinst "protoinst_files/cryptoprocessor.protoinst" -view /home/jharing/git/2nd/chw2022g3/project_1/tb_behav.wcfg -view /home/jharing/git/2nd/chw2022g3/project_1/tb_modular_mult_behav.wcfg -log simulate.log"
xsim tb_polmul_behav -key {Behavioral:sim_1:Functional:tb_polmul} -tclbatch tb_polmul.tcl -protoinst "protoinst_files/cryptoprocessor.protoinst" -view /home/jharing/git/2nd/chw2022g3/project_1/tb_behav.wcfg -view /home/jharing/git/2nd/chw2022g3/project_1/tb_modular_mult_behav.wcfg -log simulate.log

